name: immich

services:
  # Postgres database with vector support
  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - database-data:/var/lib/postgresql/data

  # Redis compatible cache
  cache:
    image: valkey/valkey:8
    container_name: immich-cache
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  # Immich server
  server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DB_HOSTNAME=database
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DATABASE_NAME=${POSTGRES_DB:-immich}
      - REDIS_HOSTNAME=cache
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
      - cache
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.rule=Host(`immich.${DOMAIN}`)
      - traefik.http.routers.immich.tls.certresolver=cloudflare

  # Immich machine learning service
  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    container_name: immich-machine-learning
    restart: unless-stopped
    volumes:
      - model-cache:/cache

networks:
  default:
    name: immich
    driver: bridge

volumes:
  database-data:
    driver: local
  model-cache:
    driver: local
